# Generated by Django 4.2 on 2025-04-26 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name_plural": "statuses"},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("number_in_queue", models.PositiveIntegerField(editable=False)),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="tracker.queue"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tracker.status"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="tasks", to="tracker.tag")),
                (
                    "watchers",
                    models.ManyToManyField(blank=True, related_name="watching_tasks", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("queue", "number_in_queue")},
            },
        ),
    ]
