# Generated by Django 4.2 on 2025-05-04 10:47

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_status_options_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="key",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_key", message="Только заглавные латинские буквы!", regex="^[A-Z]+$"
                    )
                ],
            ),
        )
    ]
